version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-deduction-unit-synonym-match-web:
    image: toposoid-deduction-unit-synonym-match-web:0.1-SNAPSHOT
    tty: true
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=172.30.0.4
      - SCALA_DATA_ACCESSOR_NEO4J_WEB_HOST=172.30.0.3
      - SENTENCE_PARSER_WEB_HOST=172.30.0.5
      - COMMON_NLP_WEB_HOST=172.30.0.6
      - PLAY_HTTP_PORT=9102
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    ports:
      - 9102:9102
    depends_on:
      - scala-data-accessor-neo4j-web
  toposoid-sentence-parser-japanese-web:
    image: toposoid/toposoid-sentence-parser-japanese-web:0.1-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.5
      - PLAY_HTTP_PORT=9001
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    ports:
      - 9001:9001
  scala-common-nlp-japanese-web:
    image: toposoid/scala-common-nlp-japanese-web:0.1-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.6
      - PLAY_HTTP_PORT=9006
    networks:
      app_net:
        ipv4_address: 172.30.0.6
    ports:
      - 9006:9006
  scala-data-accessor-neo4j-web:
    image: toposoid/scala-data-accessor-neo4j-web:0.1.1
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=172.30.0.3
      - PLAY_HTTP_PORT=9005
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 9005:9005
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:4.1.3
    environment:
      - NEO4J_AUTH=neo4j/p@ssw0rd
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      app_net:
        ipv4_address: 172.30.0.2
