version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-deduction-unit-synonym-match-web:
    image: toposoid/toposoid-deduction-unit-synonym-match-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=localhost
      - TOPOSOID_GRAPHDB_HOST=172.30.0.2
      - TOPOSOID_GRAPHDB__WEB_HOST=172.30.0.3
      - PLAY_HTTP_PORT=9102
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    ports:
      - 9102:9102
    depends_on:
      - neo4j
  scala-data-accessor-neo4j-web:
    image: toposoid/scala-data-accessor-neo4j-web:0.5-SNAPSHOT-lowspec
    environment:
      - TOPOSOID_GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=172.30.0.3
      - PLAY_HTTP_PORT=9005
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 9005:9005
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:4.4.23
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_transaction_timeout=10s
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/p@ssw0rd
    networks:
      app_net:
        ipv4_address: 172.30.0.2




